services:
  dev:
    build:
      context: ./dev
      dockerfile: Dockerfile
    # user: ${DEV_CONTAINER_UID}:${DEV_CONTAINER_GID}
    # command: sleep infinity

    volumes:
      - ./work/:/work/
      - .dev/.vscode-server:/root/.vscode-server
      # - /etc/passwd:/etc/passwd:ro
      # - /etc/group:/etc/group:ro
