services:
  dev:
    build:
      context: ./dev
      dockerfile: Dockerfile
      args:
        UID: ${DEV_CONTAINER_UID}
        GID: ${DEV_CONTAINER_GID}
    # command: sleep infinity
    volumes:
      - ./work/:/home/ubuntu/work
      - .dev/.vscode-server:/home/ubuntu/.vscode-server
      # - /etc/passwd:/etc/passwd:ro
      # - /etc/group:/etc/group:ro
